### ISSUE TITLE
Bug in recursive includes of types

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/mold#10]
Minimal example:

```yaml
recipes:
  py:
    url: 'https://github.com/scizzorz/pipenv.mold.git'
    ref: 'tmp' # bac95a63922c08c117ba56ec82e59cb4778780c0
```

And then running `mold py/clean` reports:

```
Error: couldn't locate type 'sh'
```
