### ISSUE TITLE
Some method to document which environment variables a recipe can be configured with

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/mold#29]
One of Mold's great features is the ease that you can discover which tasks can be run in a project by just typing `mold` and seeing a list of tasks.

Unfortunately, there's no way to view which variables may affect the operation of a task. I think having the ability to somehow mark a recipe as using some variables would be helpful. Possibly:

```yaml
uses:
  FLAKE_ARGS: "Additional arguments that will be passed to flake8"
  BLACK_ARGS: "Additional arguments that will be passed to black"
```
